Sandbox logs:
8704 Lambda errors have reached maximum value for submission c0ea6a1f-7b73-4ca3-a9bd-ce20f8324722


Submission logs:
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "17ed155f-8579-477f-adcd-75e9993b3fb2", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3c7d6c94-2fda-411a-8a78-1ad58bb00ed8", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b565326e-eb9f-4b9d-8f83-76fe579d8316", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ec718bcc-aac8-4704-aebd-dfbf81b11d83", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "308ce81a-9018-4e0b-8e27-6a5e79b3f8f9", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d24763d2-3bd5-46d8-a59d-9248cd6beb32", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "dc72bc72-c38a-4e96-a8be-3b7a1899e4d5", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "29f07922-d7d1-4d03-a1dd-26a16634232d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "a8ef54ee-f3bc-4601-91d8-20f742850460", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "eb9d2dec-3a39-471a-9792-2293c224c260", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d5ebe369-fa99-4f32-9d7e-3040b6b2efee", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b1f2318e-1214-4964-bed9-6bb825abd47a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "a7960671-8b99-43d4-8a64-d997b574ab7f", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "edacb0ee-cc62-46b1-a741-bc2f51442d7b", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b2e95557-26b4-4277-b102-d7ad3c09c5c9", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "5ac566c2-7724-41b3-82d3-86b3006ac0e3", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "2bec389f-0130-4d15-95e6-6c686a405888", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "84493702-6cc7-4a47-9817-7d467bab15f1", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1e5518ea-a540-4487-a766-8780adf3949c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3f0b6b9a-56f5-432c-88cd-1a3e35c259c3", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ab58f209-0cb9-4bf5-95ae-4035e508d3c7", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "0141b921-67c9-49cb-8cb2-3d3d705ebe30", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "10dad031-4c83-4e84-bf3b-0cc5e3a1aff6", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "e4b252eb-791b-4e4c-89c3-8aace0f51064", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "eaae22d0-c882-4c09-a557-598f62b910ee", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "cd1afb78-823e-4349-9c2d-a08bf5874354", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "c582b059-c5f8-465e-9d2e-771ae70b5671", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "453c642d-aaf0-4d74-a077-4672920b7e68", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d0f97c69-442d-40f5-802d-f9efd77c24da", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "57889eb1-2fd8-4d07-a1dc-f415722b974d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ac63a21a-f622-441c-b41f-554b955ba1dd", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "c2296336-8464-45aa-b40a-dd7a988cfa5e", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8ca42996-932e-421f-8fee-d9fcac63ce95", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "c4dbd635-146f-4289-9666-b13cd369db42", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "66eb6445-133f-4e68-ba41-309b35671175", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:44Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "c1e34006-39cc-40af-93ad-f2eb61f0787a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "cb64aee5-8d79-4c42-b2a8-5d708da472c0", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1a2d866a-b9da-407a-889d-2efc753a41ab", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "294e60b3-97e3-4ad2-b74d-cc1091603a4f", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "7e0b4da8-018a-44be-934f-d9f5147e5b86", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "16f6c67c-f646-46f5-8550-16c9131f045c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3648c3f9-64a8-4460-a3e0-a25324f63c1f", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "5b3f83e0-4e39-4b53-90ed-e144136bab0e", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "dd9d7dfb-28e4-4dbd-b4a8-6c16f969b6a3", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "23300db5-2eed-4811-bc26-0e7a834b8369", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1b6eb85a-d1a5-4355-b6c0-d84bf4a80b2d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6034556d-5306-468a-9048-d4046e1d894c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "4bd571d7-6055-43b8-9b02-79f5d72263ab", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "488ee4f4-fb5d-4a9d-938d-e1d5dad68545", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6de3bfff-4fdf-4a61-b91a-5a7d717ca07e", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1acc0744-b916-4e27-8ecf-986f895d6c44", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "81b32f8c-71dd-40b6-b512-f686a67b26a1", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b7c6ec94-2bd1-419f-9908-beb492b9cce3", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d0f68614-9b49-4ea3-8ec6-3658227cb49e", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "eb51e9df-429e-4a57-a1e3-09971d92808d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d115f73a-6c98-40a8-be26-de8cf0df1527", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "933a8ee9-b283-492b-8295-00194e416329", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b8cdd64c-1598-451a-b254-56701b38d888", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ba0dbaa3-9d30-4807-869d-012c117aecce", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "0474affd-3f6f-458c-8319-cb8baa9f79ce", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "412089c8-7d0c-42f5-b292-e87b01f418dc", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "9ceb17a4-928f-42da-adfe-aefc9444a13b", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "e9c1ad1a-e2b4-434f-a5f4-a160c56a589c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:45Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "bf02f3c7-35a5-404b-a0d2-24a0d0dfb17a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "38a96555-e276-4474-905f-f07d2ef65e89", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "79054ded-2406-4e20-91a4-287cad80e160", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3e624409-87c2-48c9-b51c-71ba45d577b3", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "4d24f697-05c4-4898-ba58-9f204641906a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3bed756b-0fa1-4f48-9276-dcb4945f1842", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d19da69a-e50f-4460-a017-69733b661549", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "0a9e97d2-31b1-4a5d-afd4-531ef149dfec", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "2341be8a-8895-4761-8a68-868b2cd08110", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "5297b802-c452-4e53-869f-11dede1da9b6", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ff2732cd-1e21-4072-9eba-9604a5a5e120", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "dc6448ca-79ef-46cf-8a74-3d07777ae268", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8024e232-480f-4049-abba-0e786ff6f4c5", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "07d0f54b-4d21-4054-b7a2-f87995007bfa", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ba5c621b-abfc-45ff-89d6-2394d46c557e", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "9a37a942-2a3c-475e-b4ab-4e8b32c3f55d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ca3497ee-210f-4d71-8663-b7eb954a029c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "36f0790c-8c28-4f4f-8aec-c32fcdfed189", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "47a276d0-8424-4917-b981-24633607ce14", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "121c5424-e26f-4d3b-be16-d32fa3cfc03d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ec8bf150-4d0e-4506-86c5-ee0bf06d848d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b346921e-5df6-44da-a1b3-3423db81591a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d9d87d1f-4389-4a1c-8f01-8f3f964c614a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "93f790ba-dd7a-437f-8eaa-0c30ae030024", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "916a95e1-9cd6-47d8-8584-876c8d40e935", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "243f9ded-d736-4006-9267-8cfc2f8f94d9", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d2b89b75-edc3-4d62-a6a8-327378a2d8d4", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "0368809d-3ead-452f-ac6f-eeb0d01790ba", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "a69ae23f-22c6-46a9-8e5b-07fd3f342265", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "0e00a0c6-1dba-4534-9eab-f910b60aeec6", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "4670fda3-a45c-4570-9994-902d2b15fecf", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "aac224ca-dfd0-444e-be9a-07ccfaeea260", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "4c60c0f4-c2f8-4b71-be3e-0eff8cbd1961", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "90733ffd-11be-4d32-abc3-812198c453e1", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "9d787075-cc43-474f-9ad0-fbc88de14772", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3dbcbfda-bdf1-4b5c-afe6-d6f7661005b5", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "7bd23ce0-8d1a-41ed-8e7b-66d7b625f1bb", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "edfc2ba0-bfad-4566-aebe-98b24b7cf7d8", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "22c55e10-1c04-4c98-b055-30299f8d1c3c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "bbf3fdc5-d684-4972-acff-8c7dc8a64929", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "aeff0b59-3773-4ac2-82b4-ed534d9616c3", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "fdd41e03-5b3c-489f-a6e7-21999d1f8b61", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8c98932e-5d09-4c12-9fba-45ba207379c4", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:46Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d1569145-3bd1-4654-96a9-87ce1d5c1e14", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "edce7fef-720c-4069-9abb-9ce4ba78c2cd", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8b75d717-112a-4828-b0a8-bdfd3a81ba61", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "723b304f-68ce-4016-a830-ed6636d782a4", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "fd3f722b-0411-4c13-a7fd-0adb23744b13", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "51872899-0d3c-4e95-a8c8-6abb59f89585", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "628666fb-06af-43e3-874c-59c5a266b99d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "de10dc68-bb6e-4c5e-a8bf-92d006707660", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "efacca7e-8625-4eb2-a34e-3049350c248f", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "df3ccfcf-6d0d-45c2-a8ef-068f50ed1159", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3e4d3ad9-5d30-4a66-af4f-6dfaf3510154", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "7f109bb4-2ce2-4236-ae35-9918e4440396", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "683d5149-769c-496c-b37e-0a59982ef329", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "f333a961-5775-4d78-ae98-8a084b8d980c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "e86aecba-64e6-464f-a4d4-b3773795dc60", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "44453bd6-5a21-4475-8ae3-ff19af2fb38a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "4dbc0a00-825f-44a0-b61e-fd44f953acf7", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6fa235ef-e44c-4694-bb02-11c60f0e2411", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "bdeaf894-2255-4ac6-bad9-47f30d7bf44d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "81febf59-1109-451f-9573-deff0d329004", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "419e8da2-c8c7-437a-ac03-87789b6d6ba0", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "453f3bd4-5b10-4c82-a7a8-f08d019f2b25", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8e5023bd-69aa-43eb-afa4-bc72bd8d4740", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "7669d9a8-7b4a-44eb-bb07-6a1202305d48", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "410eb8f7-cc3b-4baa-bd87-b20dfbbca995", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "78435a78-5e7f-49e3-b553-7fcd39fd873a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6014b6ee-5889-44f1-825e-73778042bfbe", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b3b87271-c0ec-43bc-ab35-0ba2d90d8845", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "f6563654-ef82-489f-a422-c7f1afcb23ef", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "602c14ea-3ef5-4a9c-b216-b605ad6c4b8b", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "fd66a22d-f757-40cc-a5ea-62450f43eea2", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "4bcb51c6-8169-4729-8408-3b09825c8ab7", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "f0fac073-de31-4bd4-baa2-5ba8d6deeae5", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "92763225-2378-40d6-9e33-8a56a842b8e6", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:47Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "728202f5-7c63-42f1-8285-ee41abbe9919", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "c6c63819-d825-4296-852c-94021a55da63", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "da6ad4e7-8565-45b3-b664-5cdb9772dab9", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "67e25cf8-4893-45ca-9b08-4e1d07beed55", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "5a3f70d8-7f0d-4691-86f4-e203ea355597", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6d181bc6-fe86-4072-b0ce-b60e5177d347", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "9991ce26-0bbd-4871-a9c3-ee16452a7404", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "fabcc23d-fd52-4e8d-93e6-52b526322706", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "231cd973-fa33-414f-a266-8d308e1061af", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b6e1bdfc-58fd-42e3-9357-30da2a400fc2", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "ac842071-d196-4c66-88dd-4b1c417154ec", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "57cde543-f9fd-464d-b79f-623c7d049a58", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "118c0b89-14fa-4a42-b5a5-47fe88358e7b", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1a9ed2ca-bbf4-482d-8875-237ed4e9e410", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "9077505d-cfc3-4c2e-911d-556969c7bcd7", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "a6414f1c-8cf1-4c92-8f94-573cff90ac9c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "c3a8d893-14e8-46d2-9bee-53811dfac4e7", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "9506af17-e7d2-414e-b641-239f86ba0884", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "7b3c7594-ea31-436b-a4ab-4d001cc0ae48", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "5c839583-d342-40ee-ad3e-86ebe8424b09", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "db8dbcd0-bb2c-4f48-bbc1-4f85c5f25267", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "59636ade-3d28-415c-a20e-ec73a3211e40", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b64a31a2-89bc-491a-bd63-0e05b955c150", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "55b28575-14c4-4f09-8352-e9363bb3dfbe", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6a79519b-e388-4ab8-8c9d-34eb7a7ef764", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "5c9a4b74-c7db-4921-9a64-bdd2054a9367", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "e67c4b9d-e0b8-4eb4-9af4-4b1b1aaaa565", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "d8e9853b-9f52-4f9a-b30d-6473568b144e", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b1a82e9b-d685-4737-b9e4-9f4c64ecaaae", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8102dde2-5b8e-4a28-83f7-26d549741a8b", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "7255b74f-21b0-49f2-b5c8-996d60a559a1", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "676eaa9d-b7c5-480b-a615-e4d6dadc0e01", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8cac3103-df78-4d5e-97e9-f9aa60a21f1b", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "11b5295b-a514-415f-93fc-2cd6d45f492c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6cb3886b-5b99-4f1b-86df-a7094601689d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "cf9574f6-bfaf-4fe0-9fb0-c52cb7aded90", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "fda12611-bcc4-420b-8d37-8210c4af0b7d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:48Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "a9659e21-a107-4b41-b1ca-6885e5ea7e5c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "3f5cdc8b-6ee2-46bc-b2ea-b507e14e924c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b2242892-39f2-419a-97b6-9eb4b60103da", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1b4bb245-eb65-4ba6-ae1b-cb1f53df225d", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "08e2a6d4-019b-4f24-a567-e8ddd5030f10", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "fe281e32-0cb9-48e0-8bff-0f6f421d8b3c", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1c42cf83-2335-4fd6-b90e-cad02e9f5fca", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "6f7a31c6-542d-42d5-bba3-b8686f211d37", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "8392eddf-6544-436b-a794-fa35f3756fee", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "45d9af92-6b77-44e5-92ed-ea1aa71d3ee2", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "82b78364-002c-40cc-9df4-1aa2d82ee98e", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "b8751b4e-081b-4701-bfb0-d5d0e3799d09", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1099b4b3-b58c-4089-bc40-d74aaaafdcd2", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "5003d202-cce7-44dd-8b18-9a2f76d8cd25", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "64b4a0f5-eaad-417c-8e56-cdc418fb92be", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "49417ea8-9664-493f-83fd-da929e5fd545", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "df8c5aa1-9f72-4a77-8a1b-af9aa293466a", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "70c7849a-bcb9-4271-8725-b787f229cd53", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "bca11159-802b-4b1b-81e3-b19405c3e3ed", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "c65965a6-f890-4887-8f53-250166394ecf", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "2ade32fd-d342-4d52-92a9-e40cb2744a21", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "087501ac-9d40-4bd9-9f29-e2e05a273219", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "1550640c-6cd2-4b2d-aba0-d7b1a8a85c00", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}
2023-03-01T18:50:49Z {"errorMessage": "stoikov_finite() takes from 4 to 5 positional arguments but 6 were given", "errorType": "TypeError", "requestId": "fbd1ec6d-735a-4aa6-b121-3aa414ece1e4", "stackTrace": ["  File \"/var/task/app.py\", line 31, in lambda_handler\n    orders = trader.run(trading_state)\n", "  File \"/var/task/trader.py\", line 58, in run\n    acceptable_price = self.stoikov_finite(product, current_position, mid_price, state.timestamp, 0.1)\n"]}